### PR TITLE
TOOLS-2473 bump jenkins-agent major version to 3

### PR DESCRIPTION
**Pull request by timfoster**

### CODE REVIEW

**Review by trentm — APPROVED** [review]
This'll be a minor or major tag version bump for joylib?

**Comment by timfoster** [comment]
I was thinking just a micro (tagging as v1.0.6) - after all, it's not changing any of the functions provided by joylib itself to hand out labels, etc. It's just changing the values in the metadata we're delivering.

**Comment by trentm** [comment]
> I was thinking just a micro (tagging as v1.0.6) - after all, it's not changing any of the functions provided by joylib itself to hand out labels, etc. It's just changing the values in the metadata we're delivering.

Sure. +1

**Comment by cburroughs** [comment]
> major version to 3

Were you able to separate the "jenkins agent" and "thing that builds stuff" images?

**Comment by trentm** [comment]
Hi @cburroughs !

> Were you able to separate the "jenkins agent" and "thing that builds stuff" images?

Nope.

**Comment by timfoster** [comment]
This bump was just to get over a build machine flag day  - we bumped the version of /opt/tools which repos with older deps/eng would deem invalid. Since the jenkins labels that jenkins-joylib handed out just specified '2', we had to bump to '3' so that jobs for old repos wouldn't get scheduled on new (now incompatible) build machines.

**Pull request merged**
